# Generated by Django 5.2.17 on 2026-09-23 22:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name_plural": "autores",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=3, unique=True, verbose_name="código CDD"
                    ),
                ),
                ("nome", models.CharField(max_length=80)),
            ],
            options={
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Membro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("telefone", models.CharField(blank=True, max_length=20)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Livro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="título")),
                ("ano", models.PositiveSmallIntegerField()),
                ("editora", models.CharField(blank=True, max_length=100)),
                (
                    "autores",
                    models.ManyToManyField(related_name="livros", to="acervo.autor"),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="livros",
                        to="acervo.categoria",
                    ),
                ),
            ],
            options={
                "ordering": ["titulo"],
            },
        ),
        migrations.CreateModel(
            name="Exemplar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="código/tombo"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("FISICO", "Físico"), ("DIGITAL", "Digital")],
                        default="FISICO",
                        max_length=7,
                    ),
                ),
                (
                    "localizacao",
                    models.CharField(max_length=60, verbose_name="localização"),
                ),
                (
                    "livro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exemplares",
                        to="acervo.livro",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "exemplares",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Emprestimo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_emprestimo",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("data_prevista", models.DateField(verbose_name="devolução prevista")),
                (
                    "data_devolucao",
                    models.DateField(
                        blank=True, null=True, verbose_name="devolvido em"
                    ),
                ),
                (
                    "multa",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("multa_paga", models.BooleanField(default=False)),
                (
                    "exemplar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="emprestimos",
                        to="acervo.exemplar",
                    ),
                ),
                (
                    "membro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="emprestimos",
                        to="acervo.membro",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_emprestimo", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("data_devolucao__isnull", True)),
                        fields=("exemplar",),
                        name="um_emprestimo_aberto_por_exemplar",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ATIVA", "Ativa (na fila)"),
                            ("ATENDIDA", "Atendida"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="ATIVA",
                        max_length=10,
                    ),
                ),
                (
                    "livro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to="acervo.livro",
                    ),
                ),
                (
                    "membro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservas",
                        to="acervo.membro",
                    ),
                ),
            ],
            options={
                "ordering": ["criada_em", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "ATIVA")),
                        fields=("livro", "membro"),
                        name="uma_reserva_ativa_por_membro_e_livro",
                    )
                ],
            },
        ),
    ]
